apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  namespace: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
      - name: serviceb
        image: mayupdocker/app-serviceb:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: serviceb
  namespace: myapp1
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '8081'
spec:
  selector:
    app: serviceb
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
